name: approved
description: A Flutter approval-tests library for quickly writing unit, widget, and integration tests.
version: 0.0.1
repository: https://github.com/buttonsrtoys/approved
issue_tracker: https://github.com/buttonsrtoys/approved/issues

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  analyzer: ^6.4.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true